apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: mpa-database
  labels:
    type: local
    app: db-cm
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/observability/data"
