apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mpa-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api
          image: ghcr.io/do3-2023/mpa-kube/api:v0.2
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: tp
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: POSTGRES_HOST
              value: db.mpa-database.svc.cluster.local
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10