apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mpa-backend
spec:
  ports:
  - name: api
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: api
  type: ClusterIP