apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: mpa-frontend
spec:
  ports:
  - name: httpweb
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31000
  selector:
    name: web
  type: NodePort