apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: mpa-database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
