name: build and publish the spin images

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-spin-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [wasm]
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download dependencies
        run: pip install -r requirements.txt

      - name: Install spin
        run: curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && sudo mv spin /usr/local/bin/
      
      - name: Build api
        run: spin build
    
      - name: Log in to ghcr with spin
        run: echo ${{ secrets.GITHUB_TOKEN }} | spin registry login -u ${{ github.actor }} --password-stdin ghcr.io

      - name: Push api image to registry
        run: spin registry push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}/${{ matrix.image }}:${{ github.ref_name }}