# Stage 1: Build the Vite application
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

COPY package.json package-lock.json ./


# Install dependencies
RUN npm install --production

# Run the application
FROM node:18-alpine as runner

WORKDIR /app

RUN npm install -g vite

COPY --from=builder /app/node_modules ./node_modules
COPY . .

CMD ["npm", "run", "dev"]
